In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df_1 = pd.read_csv("./best_model_experiment/experiments_v1/summary.csv").drop("run_id", axis=1)
df_2 = pd.read_csv("./best_model_experiment/experiments_v2/summary.csv").drop("run_id", axis=1)

for col in ["pr_auc", "recall_anomaly", "precision_anomaly", "f1_anomaly", "accuracy"]:
    if col in df_1.columns:
        df_1[col] = pd.to_numeric(df_1[col], errors="coerce")
        df_2[col] = pd.to_numeric(df_2[col], errors="coerce")

df_1

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
0,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.412067,0.000000,0.0,0.000000,0.950000,285,0,15,0
1,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.158193,0.000000,0.0,0.000000,0.950000,285,0,15,0
2,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.266851,0.000000,0.0,0.000000,0.950000,285,0,15,0
3,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.255740,0.000000,0.0,0.000000,0.950000,285,0,15,0
4,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.113739,0.000000,0.0,0.000000,0.950000,285,0,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.832332,0.666667,1.0,0.800000,0.983333,285,0,5,10
161,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.691979,0.400000,1.0,0.571429,0.970000,285,0,9,6
162,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.721663,0.066667,1.0,0.125000,0.953333,285,0,14,1
163,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.817017,0.466667,1.0,0.636364,0.973333,285,0,8,7
164,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.935892,0.600000,1.0,0.750000,0.980000,285,0,6,9

In [2]:
df_2

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
0,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.131533,0.000000,0.000000,0.000000,0.906667,272,0,28,0
1,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.079074,0.000000,0.000000,0.000000,0.906667,272,0,28,0
2,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.117795,0.000000,0.000000,0.000000,0.903333,271,0,29,0
3,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.198373,0.000000,0.000000,0.000000,0.906667,272,0,28,0
4,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.080495,0.000000,0.000000,0.000000,0.903333,271,0,29,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.562734,0.392857,0.916667,0.550000,0.940000,271,1,17,11
166,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.229023,0.142857,0.571429,0.228571,0.910000,269,3,24,4
167,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.471936,0.310345,1.000000,0.473684,0.933333,271,0,20,9
168,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.377940,0.214286,0.857143,0.342857,0.923333,271,1,22,6
169,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.253230,0.137931,0.800000,0.235294,0.913333,270,1,25,4

In [3]:
agg_1 = (
    df_1.groupby(["sweep_key", "sweep_value"], as_index=False)
        .agg(
          pr_auc_mean=("pr_auc", "mean"),
          pr_auc_std=("pr_auc", "std"),
          recall_mean=("recall_anomaly", "mean"),
          recall_std=("recall_anomaly", "std"),
          f1_mean=("f1_anomaly", "mean"),
          f1_std=("f1_anomaly", "std"),
      )
)
agg_2 = (
    df_2.groupby(["sweep_key", "sweep_value"], as_index=False)
        .agg(
          pr_auc_mean=("pr_auc", "mean"),
          pr_auc_std=("pr_auc", "std"),
          recall_mean=("recall_anomaly", "mean"),
          recall_std=("recall_anomaly", "std"),
          f1_mean=("f1_anomaly", "mean"),
          f1_std=("f1_anomaly", "std"),
      )
)

agg_1 = agg_1.sort_values(["sweep_key", "sweep_value"])
agg_2 = agg_2.sort_values(["sweep_key", "sweep_value"])
agg_1

,sweep_key,sweep_value,pr_auc_mean,pr_auc_std,recall_mean,recall_std,f1_mean,f1_std
0,ansatz,real_amplitudes,0.816191,0.095880,0.480000,0.236643,0.603286,0.262183
1,ansatz,two_local,0.818150,0.123469,0.573333,0.055205,0.721594,0.049246
2,ansatz_depth,1,0.730692,0.055992,0.493333,0.183095,0.613891,0.139141
3,ansatz_depth,2,0.799776,0.089769,0.440000,0.216465,0.576558,0.248215
4,ansatz_depth,3,0.891119,0.051478,0.573333,0.112122,0.716647,0.091914
5,feature_map,pauli_feature_map,0.241318,0.106772,0.000000,0.000000,0.000000,0.000000
6,feature_map,z_feature_map,0.814998,0.099258,0.453333,0.232584,0.579000,0.257870
7,feature_map,zz_feature_map,0.091838,0.032200,0.173333,0.127988,0.109371,0.064759
8,optimizer,adam,0.810455,0.100043,0.453333,0.232584,0.579000,0.257870
9,optimizer,cobyla,0.836745,0.049800,0.493333,0.193218,0.640249,0.170510
10,optimizer,spsa,0.772913,0.134259,0.480000,0.147358,0.627749,0.152669

In [4]:
agg_2

,sweep_key,sweep_value,pr_auc_mean,pr_auc_std,recall_mean,recall_std,f1_mean,f1_std
0,ansatz,real_amplitudes,0.386423,0.125755,0.239655,0.102291,0.366081,0.132523
1,ansatz,two_local,0.166526,0.046658,0.084483,0.037484,0.126020,0.053386
2,ansatz_depth,1,0.210241,0.030971,0.253202,0.099020,0.238181,0.068211
3,ansatz_depth,2,0.378973,0.131509,0.239655,0.102291,0.366081,0.132523
4,ansatz_depth,3,0.311185,0.073090,0.147783,0.048508,0.239756,0.077186
5,ansatz_depth,4,0.390215,0.095771,0.189409,0.085980,0.309405,0.121842
6,feature_map,pauli_feature_map,0.121454,0.045131,0.000000,0.000000,0.000000,0.000000
7,feature_map,z_feature_map,0.377944,0.132214,0.239655,0.102291,0.366081,0.132523
8,feature_map,zz_feature_map,0.161936,0.040736,0.211084,0.059067,0.164398,0.034107
9,optimizer,adam,0.382552,0.129000,0.232512,0.105216,0.356333,0.135848
10,optimizer,cobyla,0.408715,0.116645,0.232266,0.118831,0.360193,0.155563
11,optimizer,spsa,0.199838,0.146411,0.104433,0.112720,0.154329,0.173468